"""add batct_id and name to document models

Revision ID: 46912883d400
Revises: 3f793756040d
Create Date: 2025-04-28 17:47:29.956781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46912883d400'
down_revision = '3f793756040d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('batch_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('batch_name')
        batch_op.drop_column('batch_id')

    # ### end Alembic commands ###
