"""add batct_uuid to signer

Revision ID: 4787dd4f3896
Revises: 46912883d400
Create Date: 2025-05-05 16:15:05.920075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4787dd4f3896'
down_revision = '46912883d400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_uuid', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signers', schema=None) as batch_op:
        batch_op.drop_column('batch_uuid')

    # ### end Alembic commands ###
