"""Ajout des champs API key (api_key, api_key_created_at, api_key_active) au modèle User

Revision ID: 54d7852a3bfd
Revises: 
Create Date: 2025-08-21 00:42:02.089807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54d7852a3bfd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('api_key_created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('api_key_active', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint(None, ['api_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('api_key_active')
        batch_op.drop_column('api_key_created_at')
        batch_op.drop_column('api_key')

    # ### end Alembic commands ###
